# Site settings
title: Data, you have the bridge
email: adam.b.shinn -at- gmail.com
description: "Blog Description... coming soon."
baseurl: ""
url: "http://abshinn.github.io"

# Build settings
markdown: kramdown
permalink: pretty
