# Site settings
title: Data, you have the bridge
email: adam.b.shinn@gmail.com
username: abshinn
description: "Data Scientist at kWh Analytics, Inc."
baseurl: ""
url: "http://abshinn.github.io"

# Build settings
# markdown: kramdown
markdown: redcarpet
permalink: pretty
