# Site settings
title: Data, you have the bridge
email: 
username: abshinn
description: "Data science is pretty freaking awesome."
baseurl: ""
url: "http://abshinn.github.io"

# Build settings
markdown: kramdown
permalink: pretty
